### ISSUE TITLE
Variable lostLoopIterations should be incremented by the number of *inactive* threads 

### ISSUE THREAD

**Issue by xue-fc** [AlanIWBFT/CWBVH#4]
https://github.com/AlanIWBFT/CWBVH/blob/9491e2ca0289f5727fb153214ad45bb4a10f4dca/src/TraversalKernelCWBVH.cu#L365-L371
According to the paper, "Each iteration, the counter is incremented by the number of inactive threads in the warp minus a small constant Nd." So I think line 368 in this file should be "lostLoopIterations += __popc(~__activemask()) - Nd;"
 I appreciate your quick response.

**Comment by AlanIWBFT** [comment]
Nice! I was wondering why it was not very effective and this might be the culprit. Have you ever tested to see if it improves performance?
